### ISSUE TITLE
Client creates 60x90 and 90x60 px thumbnails using Media.Create, site interface upload does not

### ISSUE THREAD

**Issue by Yoonwoo** [wp-net/WordPressPCL#254]
I dont have these thumbnail sizes registered. They dont get created if I upload a file manually. Its not caused by a plugin.

**Comment by ThomasPe** [comment]
I'm pretty sure this is not something WordPressPCL does since the library just uploads an image without passing any dimensions. On my clean WordPress install for testing you can see that only the default thumbnails are created:
![image](https://user-images.githubusercontent.com/4225039/115285709-7953fb00-a14e-11eb-888f-1c63a964c91d.png)
