### ISSUE TITLE
Suggestion of create endpoint to send nonstandard requests

### ISSUE THREAD

**Issue by polushinmk** [wp-net/WordPressPCL#33]
Hi!
I have a suggestion to create the ability to send unstructured queries. This can be useful when using our plug-in to work not only with the WP REST API Core but also with the REST API plugins. For example, Contact Form 7 has its endpoint, and Woocommerce extends the standard status list (which we have hardcoded in Enums). Thus, we could give the end users of the library the opportunity to send non-standard queries.
Like that:
```
var obj = new {ID=123, Name=test};
//Get
var responce=client.CustomRequest.Get("http://mysite.com/wp-json/wp/v2/custom",obj,auth);
//Post
var responce=client.CustomRequest.Post("http://mysite.com/wp-json/wp/v2/custom",obj,auth);
//Put
var responce=client.CustomRequest.Put("http://mysite.com/wp-json/wp/v2/custom",obj,auth);
//Delete
var responce=client.CustomRequest.Delete("http://mysite.com/wp-json/wp/v2/custom",obj.ID,auth);
```

**Comment by ThomasPe** [comment]
Yes, that would certainly make sense.
I'd also like to make the library extendible by adding specific Packages like WordPressPCL.ACF (see #8), maybe this could build upon the CustomRequest-API.

I would target Milestone 1.1 since I want the current state to be released to nuget soon. Hopefully I can write some further tests for the code you've written so far.
